[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  command = "yarn build"
  functions = "netlify/functions"
  publish = ".next"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
